FROM golang:latest AS build-stage

WORKDIR /app

COPY ./go.mod ./go.sum ./go.work ./go.work.sum ./main.go ./
COPY ./src ./src

RUN CGO_ENABLED=0 GOOS=linux go build -o /kanbanapi


FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /kanbanapi /kanbanapi
ENV PORT="80"
EXPOSE 80

ENTRYPOINT ["/kanbanapi"]

